CREATE TABLE public.users(
	id INT GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1),
	email CHARACTER VARYING(320) NOT NULL,
	password CHARACTER VARYING(25) NOT NULL,
	CONSTRAINT pk_users PRIMARY KEY(id),
	CONSTRAINT uc_users_email UNIQUE(email)
);

CREATE TABLE public.employees(
	user_id INT NOT NULL,
	first_name CHARACTER VARYING(35) NOT NULL,
	last_name CHARACTER VARYING(35) NOT NULL,
	CONSTRAINT pk_employees PRIMARY KEY(user_id),
	CONSTRAINT fk_employees_users FOREIGN KEY(user_id) REFERENCES public.users(id)
);

CREATE TABLE public.candidates(
	user_id INT NOT NULL,
	first_name CHARACTER VARYING(35) NOT NULL,
	last_name CHARACTER VARYING(35) NOT NULL,
	identity_number CHARACTER VARYING(11) NOT NULL,
	date_of_birth DATE NOT NULL,
	CONSTRAINT pk_candidates PRIMARY KEY(user_id),
	CONSTRAINT fk_candidates_users FOREIGN KEY(user_id) REFERENCES public.users(id),
	CONSTRAINT uc_candidates_identity_number UNIQUE(identity_number)
);

CREATE TABLE public.employers(
	user_id INT NOT NULL,
	company_name CHARACTER VARYING(255) NOT NULL,
	web_address CHARACTER VARYING(50) NOT NULL,
	phone_number CHARACTER VARYING(12) NOT NULL,
	CONSTRAINT pk_employers PRIMARY KEY(user_id),
	CONSTRAINT fk_employers_users FOREIGN KEY(user_id) REFERENCES public.users(id)
);

CREATE TABLE public.activation_codes(
	id INT GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1),
	activation_code CHARACTER VARYING(38) NOT NULL,
	is_confirmed BOOLEAN NOT NULL,
	confirm_date DATE,
	CONSTRAINT pk_activation_codes PRIMARY KEY(id),
	CONSTRAINT uc_activation_codes_activation_code UNIQUE(activation_code)
);

CREATE TABLE public.activation_code_candidates(
	id INT NOT NULL,
	candidate_id INT NOT NULL,
	CONSTRAINT pk_activation_code_candidates PRIMARY KEY(id),
	CONSTRAINT fk_activation_code_candidates_activation_codes 
	FOREIGN KEY(id) REFERENCES public.activation_codes(id),
	CONSTRAINT fk_activation_code_candidates_candidates
	FOREIGN KEY(candidate_id) REFERENCES public.candidates(user_id)
);

CREATE TABLE public.activation_code_employers(
	id INT NOT NULL,
	employer_id INT NOT NULL,
	CONSTRAINT pk_activation_code_employers PRIMARY KEY(id),
	CONSTRAINT fk_activation_code_employers_activation_codes 
	FOREIGN KEY(id) REFERENCES public.activation_codes(id),
	CONSTRAINT fk_activation_code_employers_employers
	FOREIGN KEY(employer_id) REFERENCES public.employers(user_id)
);

CREATE TABLE public.employee_confirms(
	id INT GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1),
	employee_id INT NOT NULL,
	is_confirmed BOOLEAN NOT NULL,
	confirm_date DATE,
	CONSTRAINT pk_employee_confirms PRIMARY KEY(id),
	CONSTRAINT fk_employee_confirms_employee_id FOREIGN KEY(employee_id) REFERENCES public.employees(user_id)
);

CREATE TABLE public.employee_confirm_employers(
	id INT NOT NULL,
	employer_id INT NOT NULL,
	CONSTRAINT pk_employee_confirm_employers PRIMARY KEY(id),
	CONSTRAINT fk_employee_confirm_employers_employee_confirms 
	FOREIGN KEY(id) REFERENCES public.employee_confirms(id),
	CONSTRAINT fk_employee_confirm_employers_employers
	FOREIGN KEY(employer_id) REFERENCES public.employers(user_id)
);

CREATE TABLE public.job_positions(
	id INT GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1),
	job_title CHARACTER VARYING(255),
	CONSTRAINT pk_job_positions PRIMARY KEY(id),
	CONSTRAINT uc_job_positions_job_title UNIQUE(job_title)
);